---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: GregsNewFeature

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: rox.language
          operator: in-array
          operands:
            - hello
            - test
    flagValue: true
