---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: GregsNewFeature

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: rox.language
          operator: in-array
          operands:
            - hello
            - test
      - anyOf:
          - group:
              id: 83f5cc01-05cf-427d-561a-ed34f6655093
          - group:
              id: 3f140235-04c7-4593-78c5-4d0c61e337b3
          - group:
              id: d0e7ed70-0573-48ab-42b3-b36a59e825b2
          - group:
              id: 037f6846-2212-42ea-781f-dab5dee41e9e
          - group:
              id: d4b8b01e-bca7-41bc-5c06-ebba85162ae7
    flagValue: true
