---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: GregsNewFeature

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: rox.language
          operator: in-array
          operands:
            - hello
            - test
      - anyOf:
          - group:
              id: d4b8b01e-bca7-41bc-5c06-ebba85162ae7
          - group:
              id: a8a810be-88ae-41dc-7d2b-4a889542e732
    flagValue: true
